<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'is_admin' => true,
            'name' => 'Jabbar A. P.',
            'email' => 'jabbar@deket.in',
            'password' => bcrypt('Test1234!'),
        ]);

        User::factory()->create([
            'is_admin' => true,
            'name' => 'Dita A. P.',
            'email' => 'dita@generasicakrawala.com',
            'password' => bcrypt('Test1234!'),
        ]);

        User::factory()->create([
            'name' => 'Bukayo Saka',
            'email' => 'user@deket.in',
            'password' => bcrypt('Test1234!'),
        ]);

        DB::table('users')->insert([
            [
                'name' => 'Riyan Kurniawan',
                'email' => 'riyankurniawan2000@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6285604047628',
                'category' => 'Umum',
                'institution' => 'Umum',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Amran Mahendra Dongoran',
                'email' => 'rangamingreal@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '089620532885',
                'category' => 'Umum',
                'institution' => 'Gapyear',
                'city' => 'Surakarta',
                'is_admin' => false,
            ],
            [
                'name' => 'Jihan Mumtaz',
                'email' => 'jihanmumtaz266@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '0895611014572',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'M. Arya Wicaksana',
                'email' => 'aryawicaksna@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082361653242',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Delia Nazwa Hasibuan',
                'email' => 'delianazwahasibuan@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282246413424',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Ahmad Ibrahim Harahap',
                'email' => 'ahmadibrahim230605@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282246425292',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Ayra Jasmine Hasibuan',
                'email' => 'aeraweirdo@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282276620343',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Syahputri Mariani Hasibuan',
                'email' => 'syahputrihasibuan14@sma.belajar.id',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282244043653',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Silfi Nurfathia Ajuba',
                'email' => 'slfiajuba@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6283874653555',
                'category' => 'Umum',
                'institution' => 'SMAN 2 LUBUK PAKAM',
                'city' => 'Deli Serdang',
                'is_admin' => false,
            ],
            [
                'name' => 'Irsyah Hariyanda',
                'email' => 'irsyahhariyanda21@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6285814615090',
                'category' => 'Umum',
                'institution' => 'Bimbel Al-Khawarizmi',
                'city' => 'Palembang',
                'is_admin' => false,
            ],
            [
                'name' => 'Tasyati Nabilla',
                'email' => 'nabillatasyati@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '083878627517',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Dharmawangsa',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Sofri Yunus Zai',
                'email' => 'sofriyunuszai@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '085245657053',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Maria Nathalie Gabriella',
                'email' => 'marianathalie20@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082285442347',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Cahaya Regina Victoria Siahaan',
                'email' => 'riasiahaan789@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '081294140789',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Shefira Riani Manany',
                'email' => 'shefirariani@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282172062136',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'BUMI SATRIA',
                'email' => 'bumisatria75@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082267456221',
                'category' => 'Umum',
                'institution' => 'MAN 3 LANGKAT',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Fitra Kurniawan',
                'email' => 'fitradalimunthe.04@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '81366087776',
                'category' => 'Umum',
                'institution' => 'FIM DS',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'CINTA PUTRI DEANTI',
                'email' => 'dntcinta07@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '081263549303',
                'category' => 'Umum',
                'institution' => 'SMAN 6 MEDAN',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Mardani Syarif',
                'email' => 'mardani074@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '081344490388',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Halu Oleo',
                'city' => 'Kendari',
                'is_admin' => false,
            ],
            [
                'name' => 'Aisyah Zalfaa Ar Rahma',
                'email' => 'zalfaazifankav39@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6289690491995',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Ahmad Fauzi',
                'email' => 'ahmadfauzi1012@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282166681209',
                'category' => 'Umum',
                'institution' => 'Usu',
                'city' => 'Kupang',
                'is_admin' => false,
            ],
            [
                'name' => 'Nur Muhammad Syahid',
                'email' => 'numusya2001@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6281336542042',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Airlangga',
                'city' => 'Gresik',
                'is_admin' => false,
            ],
            [
                'name' => 'Nurul Aini',
                'email' => 'iamnurulaini25@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6289643815348',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Lampung',
                'city' => 'Bandarlampung',
                'is_admin' => false,
            ],
            [
                'name' => 'DIAH AYU DAMAYANTI',
                'email' => 'diah.ayu.damayanti09@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082268675412',
                'category' => 'Mahasiswa',
                'institution' => 'UNIVERSITAS LANCANG KUNING',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Zahra Andisha Dhanny',
                'email' => 'backupfor.zahrandisha@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282360143159',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Deli Sumatera',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Alwi Siddiq',
                'email' => 'alwisiddiq95@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '081275057867',
                'category' => 'Mahasiswa',
                'institution' => 'USU',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Wily',
                'email' => 'wily_julitawaty@yahoo.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '62895360028805',
                'category' => 'Umum',
                'institution' => 'STIE',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Elis Lintia Sipayung',
                'email' => 'elislintia@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082370764325',
                'category' => 'Mahasiswa',
                'institution' => 'USU',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Rizky Aditya Sinaga',
                'email' => 'adityaxyzr@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '89523743876',
                'category' => 'Mahasiswa',
                'institution' => 'SMA NEGERI 19 MEDAN',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Resi Triana Sari',
                'email' => 'resitrianasari@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082362276610',
                'category' => 'Umum',
                'institution' => 'RSU Mitra Medika Amplas',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Alfian Azhari',
                'email' => 'alfianhsb46@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082272504543',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'BOGOR',
                'is_admin' => false,
            ],
            [
                'name' => 'Dhan',
                'email' => 'dhantidaulay@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6281294127462',
                'category' => 'Umum',
                'institution' => '-',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Abdul Mukti',
                'email' => 'abdulmuktimedan20@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '089635735168',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Amir Hamzah Medan',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Muhammad Farhan Fauzan',
                'email' => 'farhanfauzan26@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6287775871103',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Tri Artika Sari',
                'email' => 'triartikasari87@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6281276030576',
                'category' => 'Umum',
                'institution' => 'IRT',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Rizky Wahyudi',
                'email' => 'wahyunizam2306@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '089620227958',
                'category' => 'Mahasiswa',
                'institution' => 'UNIMED',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Mely Andryani Siregar',
                'email' => 'melyandriyanisiregar@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '081377246378',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Tri Ananda Girsang, S.Pd',
                'email' => 'trianandagrsg07@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '6282163044324',
                'category' => 'Umum',
                'institution' => 'Universitas Negeri Medan',
                'city' => 'Pematangsiantar',
                'is_admin' => false,
            ],
            [
                'name' => 'Putri Delima Hasibuan',
                'email' => 'delima00.p@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '085210794919',
                'category' => 'Mahasiswa',
                'institution' => 'USU',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Renny Lutfi Syahara Damanik',
                'email' => 'rennylutfi137@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '082275876611',
                'category' => 'Mahasiswa',
                'institution' => 'UNIVERSITAS MALIKUSSALEH',
                'city' => 'Lhokseumawe',
                'is_admin' => false,
            ],
            [
                'name' => 'Angel edita n',
                'email' => 'angeledita02@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '085171668344',
                'category' => 'Mahasiswa',
                'institution' => 'Ut',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Nabila Sutari',
                'email' => 'nabilasutari31@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '62895612424345',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Malikussaleh',
                'city' => 'Deli Serdang',
                'is_admin' => false,
            ],
            [
                'name' => 'INDAH NINDARI',
                'email' => 'indahnindari414@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '+6282284456925',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Muhammadiyah Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
            [
                'name' => 'Nur Fadillah',
                'email' => 'nurfadhillh15@gmail.com',
                'password' => Hash::make("Gencar123!"),
                'phone' => '085270385857',
                'category' => 'Mahasiswa',
                'institution' => 'Universitas Sumatera Utara',
                'city' => 'Medan',
                'is_admin' => false,
            ],
        ]);
    }
}
