<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        $questions = [
            [
                'question' => 'Indonesia memiliki beberapa gunung berapi yang masih aktif, dibawah ini yang tidak termasuk gunung berapi yang masih aktif adalah...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Gunung Sumbing', 'is_correct' => true],
                    ['answer' => 'Gunung Bromo', 'is_correct' => false],
                    ['answer' => 'Gunung Tambora', 'is_correct' => false],
                    ['answer' => 'Gunung Guntur', 'is_correct' => false],
                    ['answer' => 'Gunung Tandikat', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Berapa jumlah provinsi yang ada di Indonesia saat ini?',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => '33 provinsi', 'is_correct' => false],
                    ['answer' => '34 provinsi', 'is_correct' => false],
                    ['answer' => '36 provinsi', 'is_correct' => false],
                    ['answer' => '37 provinsi', 'is_correct' => false],
                    ['answer' => '38 provinsi', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Berdasarkan letak geografisnya Indonesia terletak di antara dua benua yaitu...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Benua Australia dan Benua Afrika', 'is_correct' => false],
                    ['answer' => 'Benua Asia dan Benua Antartika', 'is_correct' => false],
                    ['answer' => 'Benua Afrika dan Benua Antartika', 'is_correct' => false],
                    ['answer' => 'Benua Asia dan Benua Australia', 'is_correct' => true],
                    ['answer' => 'Benua Amerika Utara dan Benua Eropa', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Berdasarkan letak geografisnya Indonesia terletak di antara dua samudera yaitu...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Samudera Pasifik dan Samudera Atlantik', 'is_correct' => false],
                    ['answer' => 'Samudera Hindia dan Samudera Pasifik', 'is_correct' => true],
                    ['answer' => 'Samudera Hindia dan Samudera Antartika', 'is_correct' => false],
                    ['answer' => 'Samudera Hindia dan Samudera Arktik', 'is_correct' => false],
                    ['answer' => 'Samudera Pasifik dan Samudera Antartika', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Provinsi di Indonesia yang memiliki jumlah kabupaten dan kota terbanyak, yaitu 29 kabupaten dan 9 kota adalah provinsi...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Sumatera Utara', 'is_correct' => false],
                    ['answer' => 'Nusa Tenggara Barat', 'is_correct' => false],
                    ['answer' => 'Jawa Timur', 'is_correct' => true],
                    ['answer' => 'Kalimantan Barat', 'is_correct' => false],
                    ['answer' => 'Papua Pegunungan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Tanjung Pinang adalah ibukota dari provinsi...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Kepulauan Riau', 'is_correct' => true],
                    ['answer' => 'Bengkulu', 'is_correct' => false],
                    ['answer' => 'Bangka Belitung', 'is_correct' => false],
                    ['answer' => 'Sumatera Selatan', 'is_correct' => false],
                    ['answer' => 'Riau', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pangkal Pinang adalah ibukota dari provinsi...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Kepulauan Riau', 'is_correct' => false],
                    ['answer' => 'Bengkulu', 'is_correct' => false],
                    ['answer' => 'Bangka Belitung', 'is_correct' => true],
                    ['answer' => 'Sumatera Selatan', 'is_correct' => false],
                    ['answer' => 'Riau', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pulau terbesar di Indonesia yang terletak di bagian timur negara ini adalah pulau...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Sumatera', 'is_correct' => false],
                    ['answer' => 'Kalimantan', 'is_correct' => false],
                    ['answer' => 'Jawa', 'is_correct' => false],
                    ['answer' => 'Sulawesi', 'is_correct' => false],
                    ['answer' => 'Papua', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Di bawah ini yang tidak termasuk bagian dari pulau besar di Indonesia adalah...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Sumatera', 'is_correct' => false],
                    ['answer' => 'Jawa', 'is_correct' => false],
                    ['answer' => 'Kalimantan', 'is_correct' => false],
                    ['answer' => 'Bali', 'is_correct' => true],
                    ['answer' => 'Papua', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Sungai-sungai ini berada di Pulau Kalimantan, kecuali...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Kapuas', 'is_correct' => false],
                    ['answer' => 'Serayu', 'is_correct' => true],
                    ['answer' => 'Mahakam', 'is_correct' => false],
                    ['answer' => 'Barito', 'is_correct' => false],
                    ['answer' => 'Kahayan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Gunung tertinggi di Indonesia adalah...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Gunung Merapi', 'is_correct' => false],
                    ['answer' => 'Gunung Sumbing', 'is_correct' => false],
                    ['answer' => 'Gunung Puncak Jaya', 'is_correct' => true],
                    ['answer' => 'Gunung Rinjani', 'is_correct' => false],
                    ['answer' => 'Gunung Krakatau', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Indonesia dilewati sebuah garis lintang yang berada tepat di 0°, garis tersebut dikenal sebagai garis...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Garis bujur', 'is_correct' => false],
                    ['answer' => 'Garis khatulistiwa', 'is_correct' => true],
                    ['answer' => 'Garis imajiner', 'is_correct' => false],
                    ['answer' => 'Garis bujur utama', 'is_correct' => false],
                    ['answer' => 'Garis utara', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Danau vulkanik adalah danau yang terbentuk karena letusan gunung berapi. Di bawah ini yang merupakan danau vulkanik terkenal di Indonesia adalah...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Danau Lindu (Sulawesi Tengah)', 'is_correct' => false],
                    ['answer' => 'Danau Poso (Sulawesi Tengah)', 'is_correct' => false],
                    ['answer' => 'Danau Towuti (Sulawesi Selatan)', 'is_correct' => false],
                    ['answer' => 'Danau Kelimutu (Flores, Nusa Tenggara Timur)', 'is_correct' => true],
                    ['answer' => 'Danau Tempe (Wajo, Sulawesi Selatan)', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Danau besar yang terletak di Pulau Papua dan merupakan salah satu danau terbesar di Indonesia adalah...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Danau Sentani', 'is_correct' => true],
                    ['answer' => 'Danau Toba', 'is_correct' => false],
                    ['answer' => 'Danau Maninjau', 'is_correct' => false],
                    ['answer' => 'Danau Poso', 'is_correct' => false],
                    ['answer' => 'Danau Rawa Pening', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Ibu kota Sulawesi Tenggara adalah...',
                'difficulty' => 'easy',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Kendari', 'is_correct' => true],
                    ['answer' => 'Makassar', 'is_correct' => false],
                    ['answer' => 'Kupang', 'is_correct' => false],
                    ['answer' => 'Ternate', 'is_correct' => false],
                    ['answer' => 'Tidore', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Indonesia berada di wilayah yang dikenal sebagai Ring Of Fire (Cincin Api Pasifik), yaitu sebuah jalur tektonik yang sangat aktif di sekitar tepi Samudera Pasifik. Ring of Fire mencakup sekitar 40.000 km garis panjang dengan aktivitas seismik yang tinggi, termasuk gempa bumi dan letusan gunung berapi. Berikut ini dampak yang dialami oleh negara yang berada di jalur Ring of Fire, kecuali...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Banyak sumber energi geotermal yang potensial untuk dimanfaatkan', 'is_correct' => false],
                    ['answer' => 'Minimnya aktivitas seismik dan vulkanik', 'is_correct' => true],
                    ['answer' => 'Seringnya terjadi gempa bumi dan letusan gunung berapi', 'is_correct' => false],
                    ['answer' => 'Tanah yang subur karena adanya abu vulkanik dari letusan gunung berapi', 'is_correct' => false],
                    ['answer' => 'Tingginya resiko terjadinya tsunami akibat aktivitas tektonik', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pola persebaran fauna di Indonesia dapat dibedakan menjadi tiga kelompok wilayah, yaitu wilayah fauna Indonesia tipe Asiatis, tipe Peralihan (Asia-Australis), dan tipe Australis. Manakah dibawah ini yang termasuk hewan-hewan dari tipe peralihan...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Kakatua, beo, dan walabi', 'is_correct' => false],
                    ['answer' => 'Badak bercula satu, bajing, dan elang bondol', 'is_correct' => false],
                    ['answer' => 'Maleo, anoa, dan komodo', 'is_correct' => true],
                    ['answer' => 'Kuskus, pesut, dan cendrawasih', 'is_correct' => false],
                    ['answer' => 'Orang utan, tapir, dan raja udang', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Di antara hewan-hewan langka berikut, manakah yang merupakan spesies badak yang sangat langka dengan populasi yang sangat kecil dan dilindungi di Taman Nasional Ujung Kulon?',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Orangutan (Pongo pygmaeus dan Pongo abelii)', 'is_correct' => false],
                    ['answer' => 'Harimau Sumatera (Panthera tigris sumatrae)', 'is_correct' => false],
                    ['answer' => 'Badak Jawa (Rhinoceros sondaicus)', 'is_correct' => true],
                    ['answer' => 'Burung Cendrawasih (Paradisaea spp.)', 'is_correct' => false],
                    ['answer' => 'Komodo (Varanus komodoensis)', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Batas wilayah Indonesia di sebelah utara berbatasan dengan negara-negara berikut ini, kecuali...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Malaysia', 'is_correct' => false],
                    ['answer' => 'Palau', 'is_correct' => false],
                    ['answer' => 'Filipina', 'is_correct' => false],
                    ['answer' => 'Australia', 'is_correct' => true],
                    ['answer' => 'Laut Cina Selatan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Di sebelah selatan, Indonesia berbatasan dengan negara...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Filipina', 'is_correct' => false],
                    ['answer' => 'Malaysia', 'is_correct' => false],
                    ['answer' => 'Timor Leste', 'is_correct' => true],
                    ['answer' => 'Palau', 'is_correct' => false],
                    ['answer' => 'Samudera Pasifik', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Wilayah Indonesia di sebelah barat berbatasan dengan...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Samudera Hindia', 'is_correct' => true],
                    ['answer' => 'Samudera Pasifik', 'is_correct' => false],
                    ['answer' => 'Laut Cina Selatan', 'is_correct' => false],
                    ['answer' => 'Palau', 'is_correct' => false],
                    ['answer' => 'Filipina', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Batas wilayah Indonesia di sebelah timur adalah...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Samudera Hindia', 'is_correct' => false],
                    ['answer' => 'Samudera Pasifik', 'is_correct' => true],
                    ['answer' => 'Laut Cina Selatan', 'is_correct' => false],
                    ['answer' => 'Australia', 'is_correct' => false],
                    ['answer' => 'Malaysia', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Sektor industri terutama industri manufaktur menjadi salah satu tulang punggung ekonomi negara. Berikut ini industri yang di kelola pada industri manufaktur, kecuali...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Industri kimia', 'is_correct' => false],
                    ['answer' => 'Industri elektronik', 'is_correct' => false],
                    ['answer' => 'Industri otomotif', 'is_correct' => false],
                    ['answer' => 'Industri metafisika', 'is_correct' => true],
                    ['answer' => 'Industri logam dan mesin', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Urbanisasi adalah proses perpindahan penduduk dari desa ke kota. Di Indonesia fenomena ini memiliki dampak yang signifikan terhadap perkembangan ekonomi, sosial, dan budaya. Salah satu tantangan yang muncul akibat urbanisasi yang tinggi di kota-kota besar adalah...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Peningkatan jumlah lahan pertanian', 'is_correct' => false],
                    ['answer' => 'Penurunan angka pengangguran di desa', 'is_correct' => false],
                    ['answer' => 'Peningkatan fasilitas umum di perkotaan', 'is_correct' => false],
                    ['answer' => 'Tingginya angka pengangguran di kota', 'is_correct' => true],
                    ['answer' => 'Kembali ke kehidupan yang lebih dekat dengan alam', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pola pemukiman manusia di pinggiran kota (suburban) di Indonesia umumnya memiliki karakteristik yang khas dibandingkan dengan pemukiman di desa dan kota. Salah satu karakteristik utama dari pemukiman di pinggiran kota adalah...',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Pemukiman yang tersebar dekat lahan pertanian', 'is_correct' => false],
                    ['answer' => 'Perumahan lebih tertata dibandingkan desa dengan akses mudah ke jalan utama dan transportasi menuju pusat kota', 'is_correct' => true],
                    ['answer' => 'Bangunan yang padat dan bertingkat', 'is_correct' => false],
                    ['answer' => 'Infrastruktur yang sangat terbatas', 'is_correct' => false],
                    ['answer' => 'Ruang terbuka yang luas dan alami', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Di kota Surabaya, pemerintah setempat mengimplementasikan program "Surabaya Green and Clean" yang melibatkan masyarakat dalam kegiatan penghijauan kota, pengelolaan sampah, dan daur ulang. Program ini bertujuan untuk mengurangi polusi udara dan meningkatkan kualitas lingkungan hidup. Namun, di sisi lain, kota ini juga menghadapi peningkatan jumlah kendaraan bermotor yang signifikan setiap tahunnya, yang menyebabkan peningkatan emisi gas berbahaya. Jika tren ini terus berlanjut, apa kemungkinan skenario jangka panjang yang dapat terjadi di Surabaya, meskipun program penghijauan telah diterapkan?',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Peningkatan kualitas udara di seluruh kota karena pengurangan emisi dari kendaraan bermotor', 'is_correct' => false],
                    ['answer' => 'Peningkatan jumlah lahan hijau yang otomatis menghilangkan semua polusi udara', 'is_correct' => false],
                    ['answer' => 'Penghapusan kebutuhan akan program penghijauan karena kualitas udara yang sudah membaik', 'is_correct' => false],
                    ['answer' => 'Peningkatan kesadaran masyarakat akan pentingnya pengurangan penggunaan kendaraan pribadi', 'is_correct' => false],
                    ['answer' => 'Penurunan kualitas udara di beberapa area kota akibat meningkatnya emisi kendaraan, meskipun ada upaya penghijauan', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Dalam konteks pengakuan kawasan hutan adat di Indonesia, manakah di bawah ini yang termasuk tantangan internal yang sering dihadapi oleh masyarakat adat dalam perjuangan mereka untuk melindungi dan mengelola hutan mereka?',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Adanya pertentangan dari pemerintah dan minimnya pengetahuan dari pihak masyarakat tentang terancamnya hutan adat', 'is_correct' => true],
                    ['answer' => 'Kurangnya dukungan dari masyarakat internasional dalam mempromosikan hak-hak masyarakat adat', 'is_correct' => false],
                    ['answer' => 'Kesulitan dalam mengakses teknologi modern untuk meningkatkan produktivitas pertanian di hutan adat', 'is_correct' => false],
                    ['answer' => 'Peningkatan jumlah penduduk yang mengalihkan fungsi hutan adat menjadi area pemukiman baru', 'is_correct' => false],
                    ['answer' => 'Pengurangan bantuan finansial dari lembaga donor internasional untuk proyek-proyek konservasi hutan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apakah salah satu produk ekspor utama Indonesia yang dikenal sebagai komoditas penting di pasar global?',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Elektronik dan perangkat komputer', 'is_correct' => false],
                    ['answer' => 'Produk farmasi dan obat-obatan', 'is_correct' => false],
                    ['answer' => 'Kelapa sawit', 'is_correct' => true],
                    ['answer' => 'Mobil dan kendaraan bermotor', 'is_correct' => false],
                    ['answer' => 'Bahan baku tekstil', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Di antara kota-kota berikut, manakah yang dikenal sebagai pusat industri tekstil di Indonesia?',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Jakarta', 'is_correct' => false],
                    ['answer' => 'Surabaya', 'is_correct' => false],
                    ['answer' => 'Medan', 'is_correct' => false],
                    ['answer' => 'Bandung', 'is_correct' => true],
                    ['answer' => 'Makassar', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa salah satu tindakan utama dalam konservasi hewan langka yang bertujuan untuk meningkatkan jumlah individu spesies langka melalui pembiakan di penangkaran dan reintroduksi ke habitat alami?',
                'difficulty' => 'medium',
                'category' => 'Geografi',
                'answers' => [
                    ['answer' => 'Penerapan undang-undang anti-perburuan', 'is_correct' => false],
                    ['answer' => 'Pengelolaan kawasan perlindungan', 'is_correct' => false],
                    ['answer' => 'Program pemulihan populasi', 'is_correct' => true],
                    ['answer' => 'Edukasi dan kesadaran publik', 'is_correct' => false],
                    ['answer' => 'Penyuluhan kepada petani tentang penggunaan pestisida', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Kepulauan Banda merupakan daerah penghasil pala dan fuli, rempah-rempah ini sangat menguntungkan untuk dijual di Eropa pada masa itu karena tidak dapat ditemui di tempat lain di dunia. Hal ini mengundang pedagang asing untuk mengunjungi dan menguasai sumber daya ini. Salah satunya adalah VOC, penaklukan Kepulauan Banda oleh Belanda dilancarkan oleh VOC dari tahun 1609 hingga 1621. Akibat ulah Belanda, Kepulauan Banda mengalami depopulasi yang parah. Sejarawan Vincent C. Loth dan Charles Corn memperkirakan bahwa kepulauan Banda secara keseluruhan kemungkinan memiliki jumlah penduduk sebesar 15.000 jiwa sebelum ditaklukkan oleh Belanda. Dari jumlah tersebut, hanya 1000 yang selamat. Arkeologi Peter Lape bahkan memperkirakan bahwa akibat penaklukan ini, 90 persen penduduk Kepulauan Banda tewas, diperbudak, dan dideportasi.

                Setelah menghabisi penduduk asli, VOC mengisi kembali populasi Kepuluan Banda dengan budak yang diimpor dari wilayah Nusantara lainnya, India dan Tiongkok. Menurut kisah diatas dan analisis pembaca, apa tujuan utama VOC dalam mengisi kembali populasi Kepulauan Banda setelah penaklukan?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Meningkatkan jumlah penduduk untuk kegiatan pertanian', 'is_correct' => false],
                    ['answer' => 'Memenuhi kebutuhan tenaga kerja untuk perkebunan Belanda', 'is_correct' => true],
                    ['answer' => 'Mengurangi beban sosial di daerah Nusantara lainnya', 'is_correct' => false],
                    ['answer' => 'Mengurangi ketegangan politik di wilayah jajahan', 'is_correct' => false],
                    ['answer' => 'Membangun kembali infrastruktur yang rusak', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pada 21 Juli 1947, pasukan Sekutu bersama Belanda melakukan serangan di wilayah Sumatera Utara, termasuk di Pangkalan Brandan. Penyerangan ini dimaksudkan untuk merebut tambang minyak dan wilayah strategis lainnya. Pada tanggal 13 Agustus 1947, sekitar pukul 03.00 WIB, kobaran api terjadi di Pangkalan Brandan. Para pejuang membakar tanki-tanki besar berisi crude oil, pondasi penyulingan, dan gedung-gedung perusahaan tambang minyak. Peristiwa ini dikenal sebagai Brandan Bumi Hangus, mirip dengan Bandung Lautan Api. Apa yang menjadi dampak langsung dari peristiwa Brandan Bumi Hangus terhadap strategi militer Belanda di Sumatera Utara?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Mempercepat berakhirnya Agresi Militer Belanda I', 'is_correct' => false],
                    ['answer' => 'Menghambat akses Belanda ke sumber daya minyak yang vital', 'is_correct' => true],
                    ['answer' => 'Mengubah strategi Belanda untuk fokus pada wilayah Jawa', 'is_correct' => false],
                    ['answer' => 'Memicu konflik langsung dengan Inggris di Sumatera Utara', 'is_correct' => false],
                    ['answer' => 'Mendorong Belanda untuk meningkatkan jumlah pasukan di Pangkalan Brandan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa yang menjadi latar belakang utama diterapkannya kebijakan Politik Pintu Terbuka oleh pemerintah Hindia Belanda pada tahun 1870?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Pembubaran Vereenigde Oost-Indische Compagnie (VOC) dan pengambilalihan kekuasaan oleh pemerintahan Belanda', 'is_correct' => true],
                    ['answer' => 'Keberhasilan VOC dalam mengelola ekonomi Hindia Belanda', 'is_correct' => false],
                    ['answer' => 'Kemenangan Partai Konservatif Belanda dalam pemilihan umum', 'is_correct' => false],
                    ['answer' => 'Perjanjian Sumatera yang membatasi ekspansi Belanda ke Aceh', 'is_correct' => false],
                    ['answer' => 'Kebutuhan untuk memperkenalkan sistem pendidikan modern di Hindia Belanda', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa yang menjadi salah satu tantangan utama yang dihadapi Indonesia setelah kemerdekaan sebagai akibat dari ketergantungan ekonomi yang dibangun selama penjajahan Belanda?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Kemandirian ekonomi dan diversifikasi industri', 'is_correct' => false],
                    ['answer' => 'Pengembangan sektor pendidikan yang maju', 'is_correct' => false],
                    ['answer' => 'Peningkatan kesetaraan sosial di seluruh masyarakat', 'is_correct' => false],
                    ['answer' => 'Penguatan sistem stratifikasi sosial', 'is_correct' => true],
                    ['answer' => 'Penghapusan ketergantungan pada teknologi luar negeri', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Bagaimana penjajahan Belanda memengaruhi pengembangan pendidikan di Indonesia?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Memperluas akses pendidikan bagi seluruh lapisan masyarakat', 'is_correct' => false],
                    ['answer' => 'Mendirikan universitas dan lembaga pendidikan yang tersebar di seluruh wilayah', 'is_correct' => false],
                    ['answer' => 'Mengembangkan sistem pendidikan yang terbatas untuk melayani kepentingan kolonial', 'is_correct' => true],
                    ['answer' => 'Menyediakan pendidikan gratis bagi semua penduduk pribumi', 'is_correct' => false],
                    ['answer' => 'Menghapus sistem pendidikan lokal dan menggantinya dengan sistem pendidikan internasional', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa faktor utama yang menyebabkan Dr. Christian Robert Steven Soumokil mendeklarasikan Republik Maluku Selatan (RMS) pada 25 April 1950?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Keinginan untuk bergabung dengan Negara Indonesia Timur (NIT)', 'is_correct' => false],
                    ['answer' => 'Ketidakpuasan terhadap Konferensi Meja Bundar dan dualisme politik di Ambon', 'is_correct' => true],
                    ['answer' => 'Dukungan penuh dari pemerintah Belanda', 'is_correct' => false],
                    ['answer' => 'Keputusan sepihak tanpa dukungan lokal', 'is_correct' => false],
                    ['answer' => 'Upaya untuk memperluas wilayah RMS ke pulau-pulau sekitar', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa tujuan utama pemberontakan PKI Madiun pada September 1948?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Menggulingkan pemerintahan Republik Indonesia dan mengganti sistem pemerintahan dengan komunisme', 'is_correct' => true],
                    ['answer' => 'Mengambil alih kekuasaan politik di Yogyakarta', 'is_correct' => false],
                    ['answer' => 'Menggabungkan Indonesia dengan negara-negara tetangga', 'is_correct' => false],
                    ['answer' => 'Mendirikan Negara Islam Indonesia', 'is_correct' => false],
                    ['answer' => 'Mencapai kesepakatan damai dengan Belanda', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa kontribusi Henk Sneevliet dalam serikat buruh seperti Vereeniging van Spoor-en Tramwegpersoneel (VSTP)?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Meningkatkan efisiensi administrasi serikat buruh', 'is_correct' => false],
                    ['answer' => 'Mengubah serikat buruh menjadi lebih modern dan agresif dengan melibatkan banyak anggota Indonesia', 'is_correct' => true],
                    ['answer' => 'Menghapuskan serikat buruh dan menggantinya dengan organisasi baru', 'is_correct' => false],
                    ['answer' => 'Menetapkan aturan baru tentang gaji pekerja', 'is_correct' => false],
                    ['answer' => 'Mengorganisir demonstrasi besar untuk hak-hak buruh', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa karya penting yang ditulis oleh Tan Malaka yang menggambarkan perjalanan hidup dan pemikirannya tentang revolusi Indonesia?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Kebangkitan Nasional', 'is_correct' => false],
                    ['answer' => 'Negara dan Revolusi', 'is_correct' => false],
                    ['answer' => 'Dari Penjara ke Penjara', 'is_correct' => true],
                    ['answer' => 'Pendidikan Demokrasi', 'is_correct' => false],
                    ['answer' => 'Revolusi Sosialis', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Kapan Tan Malaka kembali ke Indonesia setelah pengasingan dan bagaimana nasibnya setelah itu?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Kembali ke Indonesia pada tahun 1942, ditangkap dan dieksekusi oleh pemerintah Indonesia pada tahun 1949.', 'is_correct' => true],
                    ['answer' => 'Kembali ke Indonesia pada tahun 1945, menjadi salah satu tokoh utama dalam kemerdekaan Indonesia.', 'is_correct' => false],
                    ['answer' => 'Kembali ke Indonesia pada tahun 1948, dan mendirikan sebuah partai politik baru.', 'is_correct' => false],
                    ['answer' => 'Kembali ke Indonesia pada tahun 1949, dan kemudian menjadi presiden Indonesia pertama.', 'is_correct' => false],
                    ['answer' => 'Kembali ke Indonesia pada tahun 1950, dan mengasingkan diri di pedalaman.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Masa Bersiap adalah periode sejarah Indonesia yang penuh dengan konflik dan kekacauan setelah kemerdekaan pada tahun 1945. Masa Bersiap ditandai dengan huru-hara, pembantaian, dan perampokan massal yang dilakukan oleh masyarakat pro-kemerdekaan, seperti Pemoeda dan Pelopor. Banyak orang keturunan Belanda dan Eropa yang menjadi korban atau melarikan diri ke Eropa karena kekacauan ini. Sebagian orang Tionghoa yang mendukung partai Kuomintang juga ikut menjadi korban karena tidak mengakui kemerdekaan Indonesia. Apa faktor-faktor yang menyebabkan banyak orang keturunan Belanda dan Eropa menjadi korban kekacauan selama Masa Bersiap, dan bagaimana faktor-faktor ini menunjukkan tantangan dalam proses pembentukan negara yang baru merdeka?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Keterbatasan sumber daya untuk mengatasi konflik yang melibatkan berbagai kelompok etnis.', 'is_correct' => false],
                    ['answer' => 'Dukungan dari masyarakat lokal untuk kekacauan yang terjadi terhadap orang-orang Eropa.', 'is_correct' => false],
                    ['answer' => 'Pemberontakan yang dirancang untuk mengusir semua orang asing dari Indonesia.', 'is_correct' => false],
                    ['answer' => 'Ketidakmampuan Belanda untuk memitigasi dampak kekacauan yang telah mereka ciptakan.', 'is_correct' => false],
                    ['answer' => 'Ketidakadilan sosial dan ketidakmampuan pemerintah baru untuk melindungi semua warga negara.', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Revolusi Sosial di Sumatera Timur adalah sebuah peristiwa berdarah yang terjadi pada bulan Maret 1946, setelah proklamasi kemerdekaan Indonesia pada tahun 1945. Setelah Indonesia merdeka, terjadi perubahan iklim sistem pemerintahan di daerah-daerah, termasuk di Sumatera Timur. Gerakan kaum komunis yang ingin menghapus sistem kerajaan dengan alasan anti-feodalisme memicu revolusi sosial ini. Salah satu pemicu revolusi sosial adalah perebutan tanah bekas perkebunan kolonial Belanda, yang berdampak pada konflik agraria. Massa yang dipicu oleh kaum komunis menyerbu istana-istana kesultanan, membunuh anggota keluarga kesultanan, termasuk para penghulu dan pegawai didikan Belanda. Peristiwa ini berlangsung di beberapa daerah seperti Asahan, Panai, Kualuh, dan Langkat. Apa faktor-faktor yang memicu terjadinya pembantaian di istana-istana kesultanan selama Revolusi Sosial, dan bagaimana hal tersebut mempengaruhi pandangan masyarakat terhadap gerakan komunis?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Faktor utama adalah ketidakpuasan terhadap pemerintah kolonial yang korup. Hal ini menyebabkan masyarakat mendukung gerakan komunis tanpa memperhatikan dampak kekerasan.', 'is_correct' => false],
                    ['answer' => 'Faktor utama adalah adanya campur tangan asing dan dukungan terhadap gerakan anti-kolonial. Hal ini membuat masyarakat melihat gerakan komunis sebagai pengkhianat.', 'is_correct' => false],
                    ['answer' => 'Faktor utama adalah konflik antara pemimpin politik lokal dan nasional. Ini menyebabkan masyarakat melihat gerakan komunis sebagai pihak netral dalam konflik.', 'is_correct' => false],
                    ['answer' => 'Faktor utama adalah konflik agraria dan kebencian terhadap elit kesultanan. Hal ini menyebabkan masyarakat melihat gerakan komunis sebagai pelaku utama perubahan sosial yang diperlukan.', 'is_correct' => true],
                    ['answer' => 'Faktor utama adalah perbedaan ideologi antara golongan elit dan rakyat. Masyarakat melihat gerakan komunis sebagai pengacau yang merusak stabilitas sosial.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Poenale Sanctie adalah peraturan hukuman yang diterapkan oleh pemerintah kolonial Belanda di Hindia Belanda (sekarang Indonesia) dan Suriname pada abad ke-19. Diperkenalkan pertama kali pada tahun 1880 melalui Koelie Ordonnantie, kebijakan ini dirancang untuk mengatur dan mengontrol buruh kuli yang bekerja di perusahaan pertanian dan industri. Poenale Sanctie memberikan kekuasaan luas kepada pemilik perkebunan untuk menghukum buruh yang dianggap melanggar kontrak kerja mereka, termasuk melalui denda, hukuman fisik, dan kurungan. Kebijakan ini bertujuan melindungi kepentingan swasta Belanda dan mempertahankan kontrol kolonial dengan mencegah buruh melarikan diri. Namun, praktik ini mengakibatkan ketidakadilan dan penindasan, dengan banyak buruh yang tidak memahami kontrak kerja mereka karena buta huruf. Poenale Sanctie menimbulkan protes dan kecaman dari berbagai pihak, termasuk tokoh-tokoh Indonesia. Setelah mendapat kritik yang luas, Poenale Sanctie akhirnya dihapuskan pada tahun 1931 berkat perjuangan oleh tokoh seperti Thamrin. Penghapusan kebijakan ini menjadi langkah penting dalam reformasi sosial dan menunjukkan dampak negatif kebijakan represif terhadap struktur sosial dan ekonomi kolonial. Identifikasi dan analisis hubungan antara ketidaktahuan buruh terhadap kontrak kerja dan penerapan Poenale Sanctie dalam konteks penindasan sosial...',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Ketidaktahuan buruh terhadap kontrak kerja mempermudah penerapan Poenale Sanctie karena buruh tidak dapat membela diri secara hukum, sehingga meningkatkan penindasan sosial.', 'is_correct' => true],
                    ['answer' => 'Ketidaktahuan buruh terhadap kontrak kerja mengurangi penerapan Poenale Sanctie karena pemerintah kolonial merasa perlu untuk memberikan edukasi hukum yang lebih baik.', 'is_correct' => false],
                    ['answer' => 'Ketidaktahuan buruh terhadap kontrak kerja tidak berpengaruh pada penerapan Poenale Sanctie, karena buruh memiliki pemahaman yang cukup tentang hak-hak mereka.', 'is_correct' => false],
                    ['answer' => 'Ketidaktahuan buruh terhadap kontrak kerja memperlambat penerapan Poenale Sanctie dan meningkatkan perlindungan hukum bagi buruh.', 'is_correct' => false],
                    ['answer' => 'Ketidaktahuan buruh terhadap kontrak kerja memperbaiki penerapan Poenale Sanctie karena pemerintah kolonial menyediakan pelatihan untuk buruh tentang hak dan kewajiban mereka.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Deli Maatschappij, N.V. adalah perusahaan Belanda yang didirikan pada tahun 1869 di Deli, Sumatra Timur. Deli Maatschappij dalam industri perkebunan tembakau menarik buruh migran dari berbagai wilayah di Indonesia dan luar negeri, termasuk Jawa, Cina, dan India. Perusahaan ini memiliki pengaruh besar dalam pengembangan perkebunan tembakau di kawasan tersebut dan memainkan peran penting dalam transformasi sosial-ekonomi wilayah Sumatra Timur. Namun, di balik keberhasilan ekonomi perusahaan ini, terdapat dampak sosial yang signifikan, termasuk perubahan struktur sosial di Sumatra Timur. Bagaimana pengaruh dominasi Deli Maatschappij dalam industri perkebunan tembakau terhadap struktur sosial masyarakat Sumatra Timur, dan apa dampak jangka panjang yang diakibatkan oleh perubahan tersebut terhadap etnisitas dan hubungan antar kelompok di wilayah ini?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Terjadinya peningkatan kesejahteraan di kalangan pekerja lokal dan penguatan identitas etnis lokal.', 'is_correct' => false],
                    ['answer' => 'Pembentukan komunitas buruh migran yang beragam etnis, menyebabkan terjadinya stratifikasi sosial yang lebih kompleks di Sumatra Timur.', 'is_correct' => true],
                    ['answer' => 'Penguatan sistem kerajaan lokal yang mendukung dominasi ekonomi Belanda dan meningkatkan kesetaraan antar etnis.', 'is_correct' => false],
                    ['answer' => 'Perubahan sosial yang menghapuskan perbedaan etnis di wilayah Sumatra Timur, menciptakan masyarakat yang homogen secara budaya.', 'is_correct' => false],
                    ['answer' => 'Pembentukan elit lokal yang kaya dan berpengaruh secara ekonomi, namun tetap tunduk pada kontrol kolonial Belanda tanpa adanya perubahan signifikan pada struktur sosial.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa tujuan utama dari pendirian Deli Maatschappij di Sumatra Timur pada tahun 1869?',
                'difficulty' => 'hard',
                'category' => 'Sejarah',
                'answers' => [
                    ['answer' => 'Menyediakan lapangan kerja bagi masyarakat lokal.', 'is_correct' => false],
                    ['answer' => 'Mengembangkan industri teh di Sumatra Timur.', 'is_correct' => false],
                    ['answer' => 'Menguasai lahan perkebunan tembakau untuk kepentingan ekonomi Belanda.', 'is_correct' => true],
                    ['answer' => 'Mengurangi ketergantungan Belanda pada produk pertanian dari Eropa.', 'is_correct' => false],
                    ['answer' => 'Meningkatkan hubungan perdagangan antara Hindia Belanda dan Tiongkok.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Kebudayaan Nasional indonesia berlandasan pada',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Pancasila', 'is_correct' => false],
                    ['answer' => 'UUD 1945', 'is_correct' => true],
                    ['answer' => 'UU No.36 tahun 1999', 'is_correct' => false],
                    ['answer' => 'UU No.23 tahun 2002', 'is_correct' => false],
                    ['answer' => 'PP No. 28 Tahun 2024', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Yang termasuk unsur-unsur kebudayaan yaitu',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Bahasa dan Kesenian', 'is_correct' => true],
                    ['answer' => 'Bahasa dan Tarian', 'is_correct' => false],
                    ['answer' => 'Peralatan', 'is_correct' => false],
                    ['answer' => 'Tempat Wisata dan Sistem Keagamaan', 'is_correct' => false],
                    ['answer' => 'Sastra dan Kesenian', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Bahasa daerah yang terdapat di Indonesia sekitar',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => '724', 'is_correct' => false],
                    ['answer' => '655', 'is_correct' => false],
                    ['answer' => '665', 'is_correct' => true],
                    ['answer' => '565', 'is_correct' => false],
                    ['answer' => '760', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Di daerah Minangkabau hubungan kekerabatan didasarkan pada garis ibu yang disebut',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'patrilineal', 'is_correct' => false],
                    ['answer' => 'matrilineal', 'is_correct' => true],
                    ['answer' => 'millenial', 'is_correct' => false],
                    ['answer' => 'material', 'is_correct' => false],
                    ['answer' => 'patrial', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Senjata tradisional Badik dan Rencong berasal dari',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Jawa dan Kalimantan', 'is_correct' => false],
                    ['answer' => 'Kalimantan dan Aceh', 'is_correct' => false],
                    ['answer' => 'Jawa dan Sumatera Utara', 'is_correct' => false],
                    ['answer' => 'Betawi dan Kalimantan', 'is_correct' => false],
                    ['answer' => 'Betawi dan Aceh', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Semboyan Negara Indonesia adalah',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Garuda', 'is_correct' => false],
                    ['answer' => 'Tut Wuri Handayani', 'is_correct' => false],
                    ['answer' => 'Pancasila', 'is_correct' => false],
                    ['answer' => 'Bhinneka Tunggal Ika', 'is_correct' => true],
                    ['answer' => 'Rajin pangkal kaya', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Berdasarkan data di atas yang merupakan suku-suku yang mendiami pulau Sumatra adalah….',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => '1), 2), 4), 6)', 'is_correct' => false],
                    ['answer' => '1), 2), 6), 8)', 'is_correct' => true],
                    ['answer' => '3), 4), 6), 8)', 'is_correct' => false],
                    ['answer' => '4), 5), 7), 8)', 'is_correct' => false],
                    ['answer' => '2), 3), 5), 7)', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Tujuan dari adanya kebudayaan nasional adalah….',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'sebagai alat komunikasi', 'is_correct' => false],
                    ['answer' => 'sebagai alat interaksi', 'is_correct' => false],
                    ['answer' => 'sebagai alat perekat bangsa', 'is_correct' => true],
                    ['answer' => 'sebagai alat sosial', 'is_correct' => false],
                    ['answer' => 'sebagai alat transportasi', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pancasila merupakan salah satu identitas nasional bangsa Indonesia yang bersumber dari….',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'UUD 1945', 'is_correct' => false],
                    ['answer' => 'Sejarah bangsa Indonesia', 'is_correct' => false],
                    ['answer' => 'Konstitusi bangsa Indonesia', 'is_correct' => false],
                    ['answer' => 'Pandangan hidup dan kepribadian bangsa', 'is_correct' => true],
                    ['answer' => 'Kebudayaan yang berasal dari nenek moyang', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Rumah Gadang merupakan nama rumah adat dari….',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Sumatra Selatan', 'is_correct' => false],
                    ['answer' => 'Sumatra Barat', 'is_correct' => true],
                    ['answer' => 'Sumatra Utara', 'is_correct' => false],
                    ['answer' => 'Riau', 'is_correct' => false],
                    ['answer' => 'Bengkulu', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Salah satu warisan budaya tradisional bangsa Indonesia yang berupa kesenian yang pernah diklaim negara lain adalah….',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Kesenian Reog', 'is_correct' => true],
                    ['answer' => 'Tari Piring', 'is_correct' => false],
                    ['answer' => 'Tari Pendhet', 'is_correct' => false],
                    ['answer' => 'Sigale-gale', 'is_correct' => false],
                    ['answer' => 'Kesenian Tabuik', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Danisa dan teman-temannya berkunjung ke pasar malam. Mereka membeli kerak telur di sana. Makanan tersebut berasal dari daerah....',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'DIY Yogyakarta', 'is_correct' => false],
                    ['answer' => 'Medan', 'is_correct' => false],
                    ['answer' => 'DKI Jakarta', 'is_correct' => true],
                    ['answer' => 'Bogor', 'is_correct' => false],
                    ['answer' => 'Padang', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Ayu berasal dari Sumatera Selatan. Setiap hari dia gemar sekali memakan makanan khas daerah mereka. Apakah nama makanan daerah yang dimakan Ayu tersebut?',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Arsik', 'is_correct' => false],
                    ['answer' => 'Empek-empek', 'is_correct' => true],
                    ['answer' => 'Kerak telur', 'is_correct' => false],
                    ['answer' => 'Bakpia', 'is_correct' => false],
                    ['answer' => 'Meranti', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Putra merupakan seorang siswa yang bersuku Dayak. Putra berasal dari pulau....',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Jawa', 'is_correct' => false],
                    ['answer' => 'Bali', 'is_correct' => false],
                    ['answer' => 'Sulawesi', 'is_correct' => false],
                    ['answer' => 'Papua', 'is_correct' => false],
                    ['answer' => 'Kalimantan', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Catemak jagung merupakan makanan berbahan utama kacang-kacangan yang disertai dengan bermacam sayuran. Makanan tersebut termasuk makanan tradisional daerah....',
                'difficulty' => 'easy',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Jawa Tengah', 'is_correct' => false],
                    ['answer' => 'Nusa Tenggara Timur', 'is_correct' => true],
                    ['answer' => 'Nusa Tenggara Barat', 'is_correct' => false],
                    ['answer' => 'Sulawesi Utara', 'is_correct' => false],
                    ['answer' => 'Kalimantan Timur', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Indonesia berada di antara Benua Asia dan Benua Australia. Letak strategis tersebut menjadikan Indonesia berada di tengah-tengah lalu lintas perdagangan. Berdasarkan peristiwa tersebut, keberagaman budaya terjadi akibat pengaruhi....',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Raja-Raja Penguasa', 'is_correct' => false],
                    ['answer' => 'Pedagang Pendatang', 'is_correct' => true],
                    ['answer' => 'Pedagang Setempat', 'is_correct' => false],
                    ['answer' => 'Prajurit dari negara lain', 'is_correct' => false],
                    ['answer' => 'Masyarakat pribumi', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Wayang kulit merupakan salah satu kebudayaan tradisional tanah Jawa yang mengisahkan tentang cerita….',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Kertasana', 'is_correct' => false],
                    ['answer' => 'Bharatayuda', 'is_correct' => false],
                    ['answer' => 'Narayana', 'is_correct' => false],
                    ['answer' => 'Mahabarata', 'is_correct' => true],
                    ['answer' => 'Pandhu Dewanata', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Sasha adalah puteri dari pasangan Jawa dan Minang. Ibunya berasal dari suku Minang dengan marga Koto. Dalam konteks ini, bagaimana posisi sosial dan kultural Sasha di tengah masyarakat Minang?',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Sasha akan mewarisi marga Koto dari ibunya, menempatkannya dalam posisi penting di keluarga ibu.', 'is_correct' => true],
                    ['answer' => 'Sasha akan mengikuti marga dari ayahnya, karena budaya Minang hanya mengakui garis paternal.', 'is_correct' => false],
                    ['answer' => 'Sasha tidak akan mewarisi marga apa pun, karena campuran budaya antara Jawa dan Minang.', 'is_correct' => false],
                    ['answer' => 'Sasha dapat memilih marga dari ayah atau ibunya, tergantung pada keputusan keluarga.', 'is_correct' => false],
                    ['answer' => 'Sasha akan mendapatkan marga baru yang disesuaikan dengan gabungan tradisi Jawa dan Minang.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa yang dimaksud dengan "Indigenous culture"?',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Mencari kebudayaan di India', 'is_correct' => false],
                    ['answer' => 'Mencari kebudayaan internasional', 'is_correct' => false],
                    ['answer' => 'Mencari sesuatu yang dianggap asli', 'is_correct' => true],
                    ['answer' => 'Mencari sesuatu budaya', 'is_correct' => false],
                    ['answer' => 'Mencari karakter budaya', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Perilaku yang tidak mencerminkan sikap menghargai budaya lain adalah...',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Mengikuti tarian tradisional dari suku lain.', 'is_correct' => false],
                    ['answer' => 'Mempelajari bahasa daerah selain bahasa Indonesia.', 'is_correct' => false],
                    ['answer' => 'Menghormati perayaan hari besar keagamaan dari berbagai agama', 'is_correct' => false],
                    ['answer' => 'Menggunakan pakaian adat, namun tidak ada upaya untuk melibatkan pihak yang memiliki kekayaan budaya tersebut.', 'is_correct' => true],
                    ['answer' => 'Menggunakan produk kerajinan tangan dari berbagai daerah.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pernyataan "Tidak memandang tinggi budaya sendiri dan memandang rendah budaya lainnya" mencerminkan sikap...',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Tolerenasi', 'is_correct' => false],
                    ['answer' => 'Empati', 'is_correct' => false],
                    ['answer' => 'Apresiasi', 'is_correct' => false],
                    ['answer' => 'Persatuan', 'is_correct' => false],
                    ['answer' => 'Diskriminasi', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Perilaku yang paling tepat untuk diterapkan dalam kehidupan sehari-hari berdasarkan pernyataan-pernyataan tersebut adalah...',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Mengabaikan perbedaan budaya.', 'is_correct' => false],
                    ['answer' => 'Menutup diri terhadap budaya lain.', 'is_correct' => false],
                    ['answer' => 'Menghargai dan melestarikan semua budaya yang ada.', 'is_correct' => true],
                    ['answer' => 'Memilih-milih budaya mana yang ingin diikuti.', 'is_correct' => false],
                    ['answer' => 'Menyepelekan nilai-nilai budaya tradisional.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Nilai-nilai "tri hita karana" yang paling relevan dengan konsep pembangunan berkelanjutan adalah...',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Individualisme dan persaingan.', 'is_correct' => false],
                    ['answer' => 'Keseimbangan, harmoni, dan keberlanjutan.', 'is_correct' => true],
                    ['answer' => 'Konsumerisme dan hedonisme.', 'is_correct' => false],
                    ['answer' => 'Dominasi manusia terhadap alam.', 'is_correct' => false],
                    ['answer' => 'Pengejaran kekuasaan dan kekayaan.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Manakah pernyataan yang benar mengenai perbedaan antara gamelan Jawa dan gamelan Bali?',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Gamelan Jawa dan Bali memiliki instrumen yang sama persis, hanya berbeda dalam ukuran.', 'is_correct' => false],
                    ['answer' => 'Tangga nada gamelan Jawa dan Bali identik, sehingga menghasilkan melodi yang serupa.', 'is_correct' => false],
                    ['answer' => 'Gamelan Jawa lebih sering digunakan dalam upacara keagamaan, sedangkan gamelan Bali lebih sering digunakan dalam pertunjukan seni.', 'is_correct' => false],
                    ['answer' => 'Gaya permainan gamelan Bali cenderung lebih cepat dan dinamis dibandingkan gamelan Jawa.', 'is_correct' => true],
                    ['answer' => 'Semua pernyataan di atas salah.', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Manakah instrumen yang lebih sering ditemukan dalam gamelan Bali dibandingkan gamelan Jawa?',
                'difficulty' => 'medium',
                'category' => 'Budaya Indonesia',
                'answers' => [
                    ['answer' => 'Gong', 'is_correct' => false],
                    ['answer' => 'Kendang', 'is_correct' => false],
                    ['answer' => 'Suling', 'is_correct' => false],
                    ['answer' => 'Jegogan', 'is_correct' => true],
                    ['answer' => 'Bonang', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Forum Indonesia Muda di wilayah Sumatera Utara terbagi atas dua regional, yaitu regional ....',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Forum Indonesia Muda Regional Medan dan Deli Serdang', 'is_correct' => true],
                    ['answer' => 'Forum Indonesia Muda Regional Langkat dan Asahan', 'is_correct' => false],
                    ['answer' => 'Forum Indonesia Muda Regional Batubara dan Medan', 'is_correct' => false],
                    ['answer' => 'Forum Indonesia Muda Regional Deli Sedang dan Langkat', 'is_correct' => false],
                    ['answer' => 'Forum Indonesia Muda Regional Medan dan Labura', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pak\'E Elmir Amien dan Bunda Siti Markhamah Fauzie menjadi pelopor berdirinya Forum Indonesia Muda pada tahun ...',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => '2002', 'is_correct' => false],
                    ['answer' => '2003', 'is_correct' => true],
                    ['answer' => '2004', 'is_correct' => false],
                    ['answer' => '2005', 'is_correct' => false],
                    ['answer' => '2006', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Apa nama wadah pelatihan kepemudaan yang diselenggarakan oleh FIM Regional Medan dan Deli Serdang dan saat ini sudah memiliki tujuh angkatan.',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Generasi Burung Garuda', 'is_correct' => false],
                    ['answer' => 'Generasi Cakrawala', 'is_correct' => true],
                    ['answer' => 'Generasi Muda', 'is_correct' => false],
                    ['answer' => 'Generasi Bersama', 'is_correct' => false],
                    ['answer' => 'Generasi Dragon City', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Kegiatan membaca, review buku, dan mewarnai yang setiap bulannya dilakukan di Taman Ahmad Yani dinamakan dengan program...',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Lapak Bahagia', 'is_correct' => false],
                    ['answer' => 'Muda Belajar', 'is_correct' => false],
                    ['answer' => 'Lapak Literasi', 'is_correct' => true],
                    ['answer' => 'Belajar Menyenangkan', 'is_correct' => false],
                    ['answer' => 'Mari Belajar', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Rumah Belajar Forum Muda Indonesia Regional Deli Serdang berada di ....',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Tanjung Morawa', 'is_correct' => true],
                    ['answer' => 'Tanjung Gusta', 'is_correct' => false],
                    ['answer' => 'Tanjung Alam', 'is_correct' => false],
                    ['answer' => 'Tanjung Asri', 'is_correct' => false],
                    ['answer' => 'Tanjung Anom', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Festival yang baru saja diselenggarakan oleh Forum Indonesia Muda Regional Medan dan Deli Serdang dengan berbagai kolaborasi komunitas di wilayah Sumatera Utara disebut ....',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Comfet', 'is_correct' => false],
                    ['answer' => 'Comfest', 'is_correct' => true],
                    ['answer' => 'Comwarm', 'is_correct' => false],
                    ['answer' => 'Cosmos', 'is_correct' => false],
                    ['answer' => 'Community', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Rumah Belajar yang dinaungi oleh Forum Indonesia Regional Medan biasa disebut dengan nama ...',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Rumah Belajar Tepi Sungai', 'is_correct' => true],
                    ['answer' => 'Rumah Belajar Anak', 'is_correct' => false],
                    ['answer' => 'Rumah Belajar Pinggir Rel', 'is_correct' => false],
                    ['answer' => 'Sanggar Anak', 'is_correct' => false],
                    ['answer' => 'Rumah Belajar', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Program yang diselenggarakan dengan tujuan mengembangkan potensi diri yaitu ...',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Upgrade Diri', 'is_correct' => false],
                    ['answer' => 'Level Up', 'is_correct' => true],
                    ['answer' => 'Pelatihan', 'is_correct' => false],
                    ['answer' => 'Webinar', 'is_correct' => false],
                    ['answer' => 'Produktif', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Olahraga yang selalu dilakukan setiap minggu oleh FIM Regional Medan dan Deli Serdang, serta Generasi Cakrawala adalah....',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Sepak Bola', 'is_correct' => false],
                    ['answer' => 'Bulu Tangkis', 'is_correct' => true],
                    ['answer' => 'Tenis Meja', 'is_correct' => false],
                    ['answer' => 'Kasti', 'is_correct' => false],
                    ['answer' => 'Lari', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Kegiatan yang dipadu oleh moderator untuk mengenal setiap orang yang baru bergabung dengan FIM Regional Medan dan Deli Serdang disebut ...',
                'difficulty' => 'easy',
                'category' => 'FIM Medan',
                'answers' => [
                    ['answer' => 'Melamar', 'is_correct' => false],
                    ['answer' => 'Diskusi', 'is_correct' => false],
                    ['answer' => 'Melekat', 'is_correct' => true],
                    ['answer' => 'Merajut Kasih', 'is_correct' => false],
                    ['answer' => 'Curhatan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Indonesia memiliki ragam kebudayaan yang begitu mengagumkan dan tentu menjadi daya tarik mancanegara. Tidak jarang keunikan dari budaya tersebut telah diakui oleh UNESCO. Berikut ini adalah warisan budaya para leluhur Nusantara yang sudah diakui UNESCO, kecuali...',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Keris', 'is_correct' => false],
                    ['answer' => 'Angklung', 'is_correct' => false],
                    ['answer' => 'Wayang', 'is_correct' => false],
                    ['answer' => 'Ondel-ondel', 'is_correct' => true],
                    ['answer' => 'Gamelan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Berapa jumlah medali emas yang berhasil diraih Indonesia dalam perhelatan Olimpiade Paris 2024 ?',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => '3', 'is_correct' => false],
                    ['answer' => '2', 'is_correct' => true],
                    ['answer' => '4', 'is_correct' => false],
                    ['answer' => '5', 'is_correct' => false],
                    ['answer' => '1', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Indonesia secara resmi memegang Presidensi G20 selama 1 tahun penuh sejak 21 Desember 2021 hingga KTT G20 pada bulan November 2022 yang dilaksanakan di kota...',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Jakarta', 'is_correct' => false],
                    ['answer' => 'Bali', 'is_correct' => true],
                    ['answer' => 'Surabaya', 'is_correct' => false],
                    ['answer' => 'Lombok', 'is_correct' => false],
                    ['answer' => 'Bandung', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Rizki Juniansyah berhasil mengharumkan nama Indonesia pada Olimpiade Paris 2024 lewat cabang olahraga...',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Panjat tebing', 'is_correct' => false],
                    ['answer' => 'Lempar lembing', 'is_correct' => false],
                    ['answer' => 'Angkat Besi', 'is_correct' => true],
                    ['answer' => 'Atletik', 'is_correct' => false],
                    ['answer' => 'Panahan', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Kota di Indonesia yang menjuarai Sustainable Transport Award (STA) 2021 berkat program integrasi antarmoda transportasi publiknya adalah kota...',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Jakarta', 'is_correct' => true],
                    ['answer' => 'Surabaya', 'is_correct' => false],
                    ['answer' => 'Bandung', 'is_correct' => false],
                    ['answer' => 'Bogor', 'is_correct' => false],
                    ['answer' => 'Bali', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Tantowi Ahmad/Liliyana Natsir mendapatkan medali emas pada olimpiade tahun...',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => '2016', 'is_correct' => true],
                    ['answer' => '2020', 'is_correct' => false],
                    ['answer' => '2008', 'is_correct' => false],
                    ['answer' => '2024', 'is_correct' => false],
                    ['answer' => '2012', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pabrik pesawat terbang pertama di Asia Tenggara didirikan pada tahun 1976 oleh B.J. Habibie. Pabrik tersebut saat ini dikenal dengan nama...',
                'difficulty' => 'medium',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Pesawat Indonesia Nurtanio', 'is_correct' => false],
                    ['answer' => 'Industri Pesawat Terbang Nusantara', 'is_correct' => false],
                    ['answer' => 'Industri Pesawat Indonesia', 'is_correct' => false],
                    ['answer' => 'Industri Pesawat Nusantara', 'is_correct' => false],
                    ['answer' => 'Dirgantara Indonesia', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Indonesia pernah mengalami sebuah peristiwa penting yang disebut sebagai Proklamasi Kedua. Peristiwa ini ditandai dengan Piagam Pembentukan NKRI yang disahkan pada tanggal...',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => '13 September 1948', 'is_correct' => false],
                    ['answer' => '17 Agustus 1949', 'is_correct' => false],
                    ['answer' => '15 Agustus 1950', 'is_correct' => true],
                    ['answer' => '20 November 1966', 'is_correct' => false],
                    ['answer' => '17 Agustus 1950', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Bahasa Indonesia kini secara resmi menjadi 1 dari 10 bahasa resmi Sidang Umum UNESCO. Hal ini ditetapkan sejak tahun...',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => '2017', 'is_correct' => false],
                    ['answer' => '2019', 'is_correct' => false],
                    ['answer' => '2021', 'is_correct' => false],
                    ['answer' => '2022', 'is_correct' => false],
                    ['answer' => '2023', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Buku Fundamental of Guerrilla Warfare yang merupakan karya salah satu jendral besar Indonesia turut dijadikan buku pokok dalam pendidikan militer banyak negara di dunia. Ide,gagasan dan teori pada buku tersebut merupakan karya dan pengalaman dari...',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Soedirman', 'is_correct' => false],
                    ['answer' => 'T.B Simatupang', 'is_correct' => false],
                    ['answer' => 'A.H Nasution', 'is_correct' => true],
                    ['answer' => 'Soeharto', 'is_correct' => false],
                    ['answer' => 'Benyamin Moerdani', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Berikut ini merupakan film indonesia yang mendunia dan juga tayang di luar negeri, kecuali...',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Pengabdi Setan', 'is_correct' => false],
                    ['answer' => 'The Raid', 'is_correct' => false],
                    ['answer' => 'Marlina si Pembunuh dalam empat babak', 'is_correct' => false],
                    ['answer' => 'Gundala', 'is_correct' => false],
                    ['answer' => 'The Guys', 'is_correct' => true],
                ],
            ],
            [
                'question' => 'Pada tahun 2023, Indonesia menjadi juara umum ASEAN Para Games di Kamboja dengan perolehan total ... medali',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => '401', 'is_correct' => true],
                    ['answer' => '159', 'is_correct' => false],
                    ['answer' => '26', 'is_correct' => false],
                    ['answer' => '340', 'is_correct' => false],
                    ['answer' => '400', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Ada 2 figur Perempuan Indonesia yang masuk pada penghargaan The World\'s Most Powerful Women 2023 versi Forbes, salah satunya adalah...',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Susi Pudjiastuti', 'is_correct' => false],
                    ['answer' => 'Tri Rismaharini', 'is_correct' => false],
                    ['answer' => 'Retno Marsudi', 'is_correct' => false],
                    ['answer' => 'Sri Mulyani', 'is_correct' => true],
                    ['answer' => 'Najwa Shihab', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Siapa orang Indonesia pertama yang menaklukkan puncak gunung Everest?',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Serka Asmujiono', 'is_correct' => true],
                    ['answer' => 'Clara Sukmawati', 'is_correct' => false],
                    ['answer' => 'Norman Edwin', 'is_correct' => false],
                    ['answer' => 'Fiersa Besari', 'is_correct' => false],
                    ['answer' => 'Fransiska Dimitri Inkiriwang', 'is_correct' => false],
                ],
            ],
            [
                'question' => 'Pada tahun 1961, Soekarno menjadi salah satu dari 5 tokoh pelopor berdirinya Gerakan Non Blok untuk merespon ketegangan antara Blok Timur dan Blok Barat. 4 tokoh lainnya berasal dari negara dibawah ini, kecuali...',
                'difficulty' => 'hard',
                'category' => 'Pencapaian Indonesia',
                'answers' => [
                    ['answer' => 'Mesir', 'is_correct' => false],
                    ['answer' => 'India', 'is_correct' => false],
                    ['answer' => 'Yugoslavia', 'is_correct' => false],
                    ['answer' => 'Ghana', 'is_correct' => false],
                    ['answer' => 'Cekoslovakia', 'is_correct' => true],
                ],
            ],
        ];

        foreach ($questions as $questionData) {
            $question = DB::table('questions')->insertGetId([
                'question' => $questionData['question'],
                'difficulty' => $questionData['difficulty'],
                'category' => $questionData['category'],
            ]);

            foreach ($questionData['answers'] as $answer) {
                DB::table('answers')->insert([
                    'question_id' => $question,
                    'answer' => $answer['answer'],
                    'is_correct' => $answer['is_correct'],
                ]);
            }
        }
    }
}

